name: Discover New NPM Packages

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  issues: write

concurrency:
  group: npm-discovery
  cancel-in-progress: false

jobs:
  discover:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Discover new packages
        run: node dist/index.js discover
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Commit discovery state changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if [ -f data/discovery-state.json ]; then
            echo "Discovery state file found, committing changes..."

            # Retry logic for git operations with random delay
            max_attempts=5
            attempt=1

            while [ $attempt -le $max_attempts ]; do
              echo "Attempt $attempt/$max_attempts"

              # Pull latest changes first
              if git pull origin main --no-rebase; then
                git add data/discovery-state.json

                if git diff --staged --quiet; then
                  echo "No discovery state changes to commit"
                  break
                else
                  if git commit -m "Update package discovery state [skip ci]"; then
                    if git push; then
                      echo "Discovery state successfully committed and pushed"
                      break
                    else
                      echo "Push failed, retrying..."
                    fi
                  else
                    echo "Commit failed, retrying..."
                  fi
                fi
              else
                echo "Pull failed, retrying..."
              fi

              # Exponential backoff with jitter (1-30 seconds)
              delay=$((RANDOM % 30 + 1))
              echo "Retrying in ${delay} seconds..."
              sleep $delay
              attempt=$((attempt + 1))
            done

            if [ $attempt -gt $max_attempts ]; then
              echo "Failed to commit discovery state after $max_attempts attempts"
              exit 1
            fi
          else
            echo "WARNING: No discovery state file found - this may cause duplicate processing"
            exit 0
          fi