name: Scan NPM Packages for Security Issues

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:  # Allow manual triggering

concurrency:
  group: npm-scanning
  cancel-in-progress: true

permissions:
  contents: write
  issues: write

jobs:
  scan:
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
      fail-fast: false
    uses: ./.github/workflows/scan-packages-single.yml
    with:
      job-id: ${{ matrix.job_id }}
      total-jobs: 20

  consolidate:
    needs: scan
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all scan results
        uses: actions/download-artifact@v4
        with:
          pattern: scan-results-job-*
          path: artifacts/
          merge-multiple: true

      - name: Consolidate scan results
        run: |
          echo "Consolidating scan results from all jobs..."

          # Create data directory if it doesn't exist
          mkdir -p data

          # Count artifacts downloaded
          artifact_count=$(find artifacts/ -name "scanned-packages-new.txt" | wc -l)
          echo "Found $artifact_count scan result files"

          if [ $artifact_count -gt 0 ]; then
            # Combine all new scanned packages
            cat artifacts/*/scanned-packages-new.txt > data/all-new-scanned.txt 2>/dev/null || true

            # Sort and deduplicate, then append to main file
            if [ -f data/all-new-scanned.txt ] && [ -s data/all-new-scanned.txt ]; then
              echo "Processing $(wc -l < data/all-new-scanned.txt) new scanned packages"

              # Create or update the main scanned packages file
              touch data/scanned-packages.txt

              # Combine existing and new, sort and deduplicate
              cat data/scanned-packages.txt data/all-new-scanned.txt | sort | uniq > data/scanned-packages-updated.txt
              mv data/scanned-packages-updated.txt data/scanned-packages.txt

              # Clean up
              rm -f data/all-new-scanned.txt

              echo "Updated scanned packages file with deduplicated results"
            else
              echo "No new packages to add"
            fi
          else
            echo "No scan results found from any job"
          fi

      - name: Commit consolidated results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if [ -f data/scanned-packages.txt ]; then
            git add data/scanned-packages.txt

            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Update scanning state [skip ci]"
              git push
              echo "Successfully committed consolidated scan results"
            fi
          else
            echo "No scanned packages file to commit"
          fi